myapp/urls.py
from os import name
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name_en>', views.CategoryDetail.as_view(), name='category_detail'),
    path('search', views.Search, name='search'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category = self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = models.TextField('内容', max_length=1000)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name='投稿', on_delete=models.PROTECT)
    user = models.ForeignKey(
        User, verbose_name='Likeしたユーザー', on_delete=models.PROTECT)

myapp/forms.py
from django import forms
from django.db.models import fields
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'thumbnail')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs['class'] = 'form-control'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs['class'] = 'form-control'

class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.db.models.query_utils import Q
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, resolve_url
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic import detail
from .models import Post, Like, Category
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user


class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Postを登録しました。')
        return resolve_url('myapp:index')


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(
            category=detail_data.category).order_by('-created_at')[:5]
        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, '記事を更新しました。')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])


class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.info(self.request, '投稿を削除しました。')
        return resolve_url('myapp:index', )


class PostList(ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'


class Logout(LogoutView):
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'ユーザー登録しました。')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)

    is_liked = Like.objects.filter(user=request.user, post=post_id).count()
    if is_liked > 0:
        messages.info(request, 'お気に入りに追加済みです。')
        return redirect('myapp:post_detail', post_id)

    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, 'お気に入りに追加しました！')
    return redirect('myapp:post_detail', post_id)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(
            category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }
        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(
                Q(title__icontains=freeword) | Q(content__icontains=freeword))

        params = {
            'search_list': search_list,
        }

        return render(request, 'myapp/search.html', params)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{{ request.site.siteconfig.meta_title }}</title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

  <!-- Your custom styles (optional) -->
  <!-- <link href="css/style.css" rel="stylesheet"> -->
</head>

<body>

  <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-dark indigo">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="/">Hag Blog</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'myapp:index' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin" target="_blank">Admin</a>
        </li>
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="account" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Account</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="account">

            {% if request.user.is_authenticated %}
            <a class="dropdown-item">{{ request.user }}</a>
            <a class="dropdown-item" href="{% url 'myapp:logout' %}">ログアウト</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'myapp:login' %}">ログイン</a>
            <a class="dropdown-item" href="{% url 'myapp:signup' %}">ユーザー登録</a>
            {% endif %}

          </div>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Post</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'myapp:post_create' %}">新規投稿</a>
            <a class="dropdown-item" href="{% url 'myapp:post_list' %}">投稿一覧</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Category</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">

            {% for item in category_list %}
            <a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a>
            {% endfor %}
            <hr>
            <a class="dropdown-item" href="{% url 'myapp:category_list' %}">カテゴリ一覧</a>
          </div>
        </li>


      </ul>
      <!-- Links -->

      <form action="{% url 'myapp:search' %}" class="form-inline" method="POST">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="freeword">
      </form>
    </div>
    <!-- Collapsible content -->

  </nav>
  <!--/.Navbar-->


  <main class="container">

    {% if messages %}
    <br>
    {% for message in messages %}

    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock content %}


  </main>


  <!-- Footer -->
  <footer class="page-footer font-small indigo pt-4">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase">Footer Content</h5>
          <p>Here you can use rows and columns to organize your footer content.</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

  <!-- /Start your project here-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>

</html>

myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>{{ object.name }}</h2>
    <hr>
    <ul class="list-group">
      {% for item in category_posts %}
      <li class="list-group-item"><a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a></li>
      {% endfor %}
    </ul>
    <br>

  </div>

</div>
{% endblock content %}

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>Category List</h2>
    <br>
  </div>
</div>
<div class="row">
  {% for category in category_list %}
  <div class="col-md-4">
    <br>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'myapp:category_detail' category.name_en %}" style="color:rgb(9, 62, 112)">{{ category.name }}</a> &nbsp;<small>[&nbsp;{{ category.post_count }}記事&nbsp;]</small></h4><hr><br>
        {% for post in category.post_set.all|slice:":5" %}
        <p><a href="{% url 'myapp:post_detail' post.id %}" style="color: rgb(79, 11, 189);">{{ post.title }}</a></p>
        {% endfor %}
        <br><br>
        <a href="{% url 'myapp:category_detail' category.name_en %}" style="color:rgb(9, 62, 112)">このカテゴリの記事を全て見る</a>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
<br>

{% endblock content %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}


{% block content %}
<!-- Start your project here-->
<div class="jumbotron card card-image" style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
    <!-- "jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5" -->
    <!-- Title -->
    <h2 class="card-title h2">{{ request.site.siteconfig.top_title }}</h2>

    <!-- Subtitle -->
    <p class="my-4 h6">{{ request.site.siteconfig.top_subtitle }}</p>

    <!-- Grid row -->
    <div class="row d-flex justify-content-center">

        <!-- Grid column -->
        <div class="col-xl-7 pb-2">

            <p class="card-text"></p>

        </div>
        <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <!-- <hr class="my-4 rgba-white-light">

    <div class="pt-2">
        <button type="button" class="btn btn-outline-white">Buy now <i class="far fa-gem ml-1"></i></button>
        <button type="button" class="btn btn-outline-white">Download <i class="fas fa-download ml-1"></i></button>
    </div> -->

</div>
<!-- Jumbotron -->

<div class="row">
    <!-- Card deck -->
    <div class="card-deck">

        {% for item in post_list %}
        <div class="col-md-4">

            <!-- Card -->
            <div class="card mb-4">

                <!--Card image-->
                <div class="view overlay">

                    {% if item.thumbnail %}
                    <img class="card-img-top" src="{{ item.thumbnail.url }}"
                    alt="{{ item.title }}">

                    {% else %}
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg"
                        alt="{{ item.title }}">

                    {% endif %}
                    <a href="{% url 'myapp:post_detail' item.id %}">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <!--Card content-->
                <div class="card-body">

                    <!--Title-->
                    <h4 class="card-title">{{ item.title }}</h4>
                    <p>{{ item.category }}</p>
                    <!--Text-->
                    <p class="card-text">{{ item.content|safe|truncatechars_html:50}}</p>
                    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                    <a href="{% url 'myapp:post_detail' item.id %}" type="button" class="btn btn-blue btn-md">もっと読む</a>
                </div>

            </div>
            <!-- Card -->

        </div>
        {% endfor %}

    </div>
    <!-- Card deck -->

</div>
{% endblock content %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-4">
    <br>
    <h2>Login</h2>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      {{ field.label}}
      {{ field }}
      {{ field.errors }}
      <br>
      {% endfor %}
      <button type="submit" class="btn btn-primary">ログイン</button>
      <br><br>
    </form>
  </div>

</div>
{% endblock content %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-6">
    <br>
    <h2>Logout</h2>
    <br>
    <p>ログアウトしました</p>
  </div>

</div>
{% endblock content %}

myapp/templates/myapp/pagination.html
<div class="pagination">
  <span class="step-links">

    {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>

</div>

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>Post削除</h2>
    <br>
    <div class="alert alert-danger" role='alert'>
      <form action="" method="post">
        {% csrf_token %}
        <p>以下の内容を本当に削除しますか？</p>
        <input type="submit" class="btn btn-danger" value="削除する">
      </form>
    </div>
    <br>
    <p>タイトル</p>
    {{ object.title }}
    <hr>
    <p>内容</p>
    {{ object.content }}
    <br>
    <br>
    <br>

  </div>

</div>
{% endblock content %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}


{% block content %}

<div class="row">
  <div class="col-md-9">
    <br>

    <!-- Card -->
    <div class="card">

      <!-- Card image -->

      {% if object.thumbnail %}
      <img class="card-img-top" src="{{ object.thumbnail.url }}" alt="{{ object.title }}">
      {% else %}
      <img class="card-img-top" src="" alt="Card image cap">
      {% endif %}



      <!-- Card content -->
      <div class="card-body">

        <!-- Title -->
        <h4 class="card-title"><a>{{ object.title }}</a></h4>
        <!-- Text -->
        <p class="card-text">{{ object.content | safe | linebreaksbr |urlize }}</p>
        <!-- Button -->
        <a class="btn" href="{% url 'myapp:like_add' object.pk %}" style="background-color: #ff6699; color:white;">お気に入りに登録</a>
        <hr>
        <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-dark">戻る</a>

        {% if object.author == request.user %}
        <a href="{% url 'myapp:post_update' object.pk %}" class="btn btn-primary">更新</a>
        <a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-danger">削除</a>
        {% endif %}

      </div>

    </div>
    <!-- Card -->
    <br>
  </div>

  <div class="col-md-3">
    <br>
    <!-- Card -->
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ object.category }}</h5>
        <p>このカテゴリの記事</p>
      </div>
      <ul class="list-group">

        {% for item in category_posts %}
        <li class="list-group-item"><a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a></li>

        {% endfor %}


      </ul>



    </div>
    <!-- Card -->

  </div>

</div>

{% endblock content %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>Post登録・更新</h2>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="">タイトル</label>
        {{ form.title }}
      </div>
      <div class="form-group">
        <label for="">カテゴリ</label>
        {{ form.category }}
      </div>
      <div class="form-group">
        <label for="">サムネル画像</label>
        {{ form.thumbnail }}
      </div>
      <br>
      <div class="form-group">
        <label for="">内容</label>
        {{ form.content }}
      </div>
      <br>

      <button type="submit" class="btn btn-primary">保存</button>

    </form>
  </div>

</div>
{% endblock content %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>記事一覧</h2>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th width="250px"><b>タイトル</b></th>
          <th width="600px"><b>内容</b></th>
          <th width="200px"><b>作成日時<br>更新日時</b></th>
        </tr>
      </thead>
      <tbody>

        {% for item in post_list  %}
        <tr>
          <td><a href="{% url 'myapp:post_detail' item.pk%}">{{item.title}}</a></td>
          <td>{{ item.content |safe|truncatechars_html:50}}</td>
          <td>{{ item.created_at.date }}
          <br>
            {{ item.updated_at.date }}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
    <br>
    {% include 'myapp/pagination.html' %}
    <br>
  </div>

</div>
{% endblock content %}

myapp/templates/myapp/search.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>記事一覧</h2>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>作成日時</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <tbody>

        {% for item in search_list  %}
        <tr>
          <td><a href="{% url 'myapp:post_detail' item.pk%}">{{item.title}}</a></td>
          <td>{{ item.content }}</td>
          <td>{{ item.created_at }}</td>
          <td>{{ item.updated_at }}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
    <br>
  </div>

</div>
{% endblock content %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-6">
    <br>
    <h2>Signup</h2>
    <br>

    <form action="" method="post">
      {% csrf_token %}

      {{ form.non_field_errors }}

      {% for field in form  %}
          {{ field.label}}
          {{ field }}
          {{ field.errors }}
          <br>
      {% endfor %}

      <button type="submit" class="btn btn-primary">サインアップ</button>
      <br><br>

    </form>
  </div>

</div>
{% endblock content %}